### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by marefr** [Daniel15/JSPool#11]
Using React.NET 2.2.1 (https://github.com/reactjs/React.NET). 

Been running some load tests with locust.io. Basically doing a lot of continuous requests against one specific url in our ASP.NET MVC web application. Sometimes I can run the load test for hours without any failures, but sometimes I'm starting to get failures because of the following exception being thrown. 

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
 at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at JSPool.JsPool.CreateEngine()
   at JSPool.JsPool.GetEngine(Nullable`1 timeout)
   at React.JavaScriptEngineFactory.GetEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at React.ReactEnvironment.get_Engine()
   at React.ReactEnvironment.EnsureUserScriptsLoaded()
   at React.ReactEnvironment.CreateComponent[T](String componentName, T props, String containerId)
   at React.Web.Mvc.HtmlHelperExtensions.React[T](HtmlHelper htmlHelper, String componentName, T props, String htmlTag, String containerId, Boolean clientOnly, Boolean serverOnly, String containerClass)
   at ASP._Page_Views_SomeController_Index_cshtml.Execute() in C:\Something\Views\Some\Index.cshtml:line 8
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.StartPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
```

I will add that when you've received one of these exceptions the likelyhood to receive more of them are higher, like they're growing exponentially.

Any idea of what's going on or why this is happening?

**Comment by Daniel15** [comment]
Looks like this was related to #13, which should be fixed in version 0.3.2.
